sudo: required
dist: trusty

# Compiler selection
compiler:
  - clang
  - gcc


addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.8
    - libc++-dev

before_install:
- sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y
- sudo apt-get update -qq
- sudo apt-get install -y libphysfs-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
- sudo apt-get install -y --no-install-recommends doxygen valgrind graphviz
- export CC="gcc-5"
- export CXX="g++-5"
-language: generic
script:
- clang++ --version
- make -f Makefile.Linux clang -j4
- make all test -j4 

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bf24f1666021dc4df89a
    on_success: never  # options: [always|never|change] default: always
    on_failure: never  # options: [always|never|change] default: always
    on_start:   false   # default: false
