before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y
- sudo apt-get update -qq
- if [ "$CC" = "gcc" ];  then sudo apt-get install -qq -y gcc-4.9; fi
- if [ "$CC" = "gcc" ];  then export CC="gcc-4.9" CC="gcc-4.9"; fi
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq -y g++-4.9; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
- sudo apt-get install -y libphysfs-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libenet-dev
- sudo apt-get install -y --no-install-recommends doxygen valgrind graphviz
language: cpp
script:
- make all test -j4

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bf24f1666021dc4df89a
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start:   false   # default: false
