clone_depth: 1

platform:
    - win32
    - x64
configuration:
    - Debug
    - Release

install:
    git submodule update --init --recursive --depth 1

before_build:
    set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
    
build:
    parallel: true                  # enable MSBuild parallel builds
    project: egoboo.sln             # path to Visual Studio solution or project

test_script:
    - ps: |
        $platform = $env:platform
        if ($platform -eq "Win32") { $platform = "x86" }
        vstest.console /Logger:Appveyor /Platform:$platform /inIsolation "product\egolib-tests\$env:configuration\$env:platform\egolib-tests.dll"

notifications:
    - provider: Webhook
      url: https://webhooks.gitter.im/e/7743b26cbf1767e7b3a3
      on_build_success: true
      on_build_failure: true
