# AppVeyor configuration for AppVeyor project "Egoboo Nightly".
clone_depth: 1

platform:
    - Win32
    - x64
configuration:
    - Debug
    - Release
    
skip_tags: true
    
branches:
  only:
    - master
    
init:
    - ps: Update-AppveyorBuild -Version "$(Get-Date -format yyyy-MM-dd)"

install:
    git submodule update --init --recursive --depth 1

before_build:
    set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
    
# Artifacts are produced by the AppVeyor project "Egoboo Nightly".
after_build:
    7z a binaries-%CONFIGURATION%-%PLATFORM%-%APPVEYOR_BUILD_VERSION%.zip product\game\%CONFIGURATION%\%PLATFORM%\*.dll product\game\%CONFIGURATION%\%PLATFORM%\*.exe
 
build:
    parallel: true                  # enable MSBuild parallel builds
    project: egoboo.sln             # path to Visual Studio solution or project

test_script:
    - ps: |
        $platform = $env:platform
        if ($platform -eq "Win32") { $platform = "x86" }
        vstest.console /Logger:Appveyor /Platform:$platform /inIsolation "product\egolib-tests\$env:configuration\$env:platform\egolib-tests.dll"

# if one matrix entry fails, all entries fails
# https://www.appveyor.com/docs/build-configuration#failing-strategy
matrix:
    fast_finish: true
        
notifications:
    - provider: Webhook
      url: https://webhooks.gitter.im/e/7743b26cbf1767e7b3a3
      on_build_success: true
      on_build_failure: true
      
# Artifacts are produced by the AppVeyor project "Egoboo Nightly".
artifacts:
    - path: binaries-Debug-Win32-$(appveyor_build_version).zip
      name: binaries-Debug-Win32$-(appveyor_build_version)
    - path: binaries-Debug-x64-$(appveyor_build_version).zip
      name: binaries-Debug-x64-$(appveyor_build_version)
    - path: binaries-Release-Win32-$(appveyor_build_version).zip
      name: binaries-Release-Win32-$(appveyor_build_version)
    - path: binaries-Release-x64-$(appveyor_build_version).zip
      name: binaries-Release-x64-$(appveyor_build_version)

deploy:
    - provider: FTP
      protocol: ftp
      host: cdn.primordialmachine.com
      username: ftp11220059-CdnPrimordialMachine
      password:
        secure: O78JuCX9OUvHgwWYdGsDyJhteWurb5Tq8AAWAjjWgOE=
      artifact: binaries-Debug-Win32-$(appveyor_build_version) binaries-Debug-x64-$(appveyor_build_version) binaries-Release-Win32-$(appveyor_build_version) binaries-Release-x64-$(appveyor_build_version)
    - provider: GitHub
      tag: Egoboo-Nightly
      release: Egoboo-Nightly
      description: 'Egoboo Nightly'
      force_update: true
      auth_token:
        secure: kxr/+rin/StoIdTBFp4+OG+nxeoI1TGjLYiPXgttgjyjcDy/3V+G10AAukyTxDIx
      artifact: binaries-Debug-Win32-$(appveyor_build_version) binaries-Debug-x64-$(appveyor_build_version) binaries-Release-Win32-$(appveyor_build_version) binaries-Release-x64-$(appveyor_build_version)
      draft: false
      prerelease: false
      on:
        appveyor_repo_tag: false