os: Visual Studio 2014 CTP4

platform:
    - win32
    - x64
configuration:
    - Debug
    - Release

install:
    git submodule update --init --recursive

build:
    project: egoboo_vs13.sln

test:
    assemblies:
        - product\egolib-tests\$(configuration)\$(platform)\egolib-tests.dll

notifications:
    - provider: Webhook
      url: https://webhooks.gitter.im/e/7743b26cbf1767e7b3a3
      on_build_success: true
      on_build_failure: true
