os: Visual Studio 2014 CTP4

platform:
    - win32
    - x64
configuration:
    - Debug
    - Release

install:
    git submodule update --init --recursive

build:
    project: egoboo_vs13.sln

test:
    assemblies:
        - egolib-tests.dll

notifications:
    - provider: Webhook
        url: https://webhooks.gitter.im/e/4b232f176269cf9f24bd
