# AppVeyor configuration for AppVeyor project "Egoboo".
clone_depth: 1

platform:
    - Win32
    - x64
configuration:
    - Debug
    - Release

install:
    git submodule update --init --recursive --depth 1

before_build:
    set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

# Artifacts are produced by the AppVeyor project "Egoboo Nightly".
#after_build:
    #7z a binaries-%CONFIGURATION%-%PLATFORM%.zip product\game\%CONFIGURATION%\%PLATFORM%\*.dll product\game\%CONFIGURATION%\%PLATFORM%\*.exe
 
build:
    parallel: true                  # enable MSBuild parallel builds
    project: egoboo.sln             # path to Visual Studio solution or project

test_script:
    - ps: |
        $platform = $env:platform
        if ($platform -eq "Win32") { $platform = "x86" }
        vstest.console /Logger:Appveyor /Platform:$platform /inIsolation "product\egolib-tests\$env:configuration\$env:platform\egolib-tests.dll"

# if one matrix entry fails, all entries fails
# https://www.appveyor.com/docs/build-configuration#failing-strategy
matrix:
    fast_finish: true
        
notifications:
    - provider: Webhook
      url: https://webhooks.gitter.im/e/7743b26cbf1767e7b3a3
      on_build_success: true
      on_build_failure: true

# Artifacts are produced by the AppVeyor project "Egoboo Nightly".
#artifacts:
#    - path: binaries-Debug-Win32.zip
#      name: binaries-Debug-Win32
#    - path: binaries-Debug-x64.zip
#      name: binaries-Debug-x64
#    - path: binaries-Release-Win32.zip
#      name: binaries-Release-Win32
#    - path: binaries-Release-x64.zip
#      name: binaries-Release-x64
